# Generated by Django 3.2.6 on 2021-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDBTitleSearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TV', 'TV'), ('MO', 'Movie')], max_length=2)),
                ('title', models.CharField(max_length=512)),
                ('rating', models.CharField(max_length=32)),
                ('blurb', models.TextField()),
                ('imdb_title_url', models.CharField(max_length=256)),
                ('find_results', models.TextField()),
                ('file_path', models.CharField(max_length=512)),
                ('file_mtime', models.BigIntegerField()),
                ('file_ctime', models.BigIntegerField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
