# Generated by Django 3.2.6 on 2021-08-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_info_local', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdbtitlesearchdata',
            name='imdb_title_url',
        ),
    ]
