# Generated by Django 3.2.6 on 2021-08-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_info_local', '0002_remove_imdbtitlesearchdata_imdb_title_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbtitlesearchdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='title-images/'),
        ),
    ]
