# Generated by Django 4.1.3 on 2023-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_info_local', '0003_imdbtitlesearchdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbtitlesearchdata',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
